// Generated by CoffeeScript 1.2.1-pre-peick
(function() {
  var key, val, _ref;

  _ref = require('./coffee-script');
  for (key in _ref) {
    val = _ref[key];
    exports[key] = val;
  }

}).call(this);
